apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-topology: 2x2x1
        cloud.google.com/gke-tpu-accelerator: tpu7x
      containers:
      - name: inference-server
        resources:
          requests:
            google.com/tpu: 4
          limits:
            google.com/tpu: 4
