apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        karpenter.azure.com/sku-gpu-name: H100
      tolerations:
        - key: "nvidia.com/gpu"
          operator: Exists
          effect: NoSchedule
      containers:
      - name: inference-server
        resources:
          requests:
            cpu: "8"
            memory: "64Gi"
            nvidia.com/gpu: 1
          limits:
            memory: "100Gi"
            nvidia.com/gpu: 1
