apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored-here
spec:
  template:
    spec:
      nodeSelector:
        $patch: replace
        eks.amazonaws.com/compute-type: auto
      containers:
      - name: inference-server
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        env:
          - name: TENSOR_PARALLEL_SIZE
            value: "1"
